---
title: "Code-along, Week 01: Emmy nominees"
author: "Alex Homer"
date: "23 September 2021"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r load-packages, message = FALSE}
library(tidyverse)
```

## Read data
The data are drawn from the "Tidy Tuesday" project: [2021 Week 39: Emmy Awards and Nominees](https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-09-21/readme.md) (credit: [Emmys website](https://www.emmys.com/awards/nominations/award-search)/[Susie Lu](https://www.susielu.com/data-viz/emmy-2017)).  They have been lightly cleaned.

```{r read-data, message = FALSE}
nominees <- readRDS("data/nominees_clean.rds")
```

## Who won the most Emmys?
```{r winner, message = FALSE}
winners <- nominees %>%
  filter(type == "Winner") %>%
  select(-type)

(
  winners_count <- winners %>%
    count(title, sort = TRUE)
)
```

Game of Thrones won the most Emmys.  Let's see a graph!

```{r winner-plot, message = FALSE}
#First make a new data frame with an "other" category.
cutoff <- 60

winners_count %>% filter(n >= cutoff) %>%
  mutate(title = fct_reorder(title, n)) %>%
  ggplot(aes(x = n, y = title)) +
  geom_col() +
  labs(
    x = "Number of wins",
    y = "Show",
    title = "Shows with most Emmy wins",
    subtitle = paste("Shows with more than", cutoff, "wins shown"),
    caption = "Source: Emmys website/Susie Lu"
  ) +
  theme_minimal()
```